apiVersion: v1
kind: Pod
metadata:
  name: iperf-client
spec:
  containers:
  - name: iperf-client
    image: iperf-dev-1
    #ports:
      #- containerPort: 5201
    imagePullPolicy: IfNotPresent
    #command: ["printenv"] # is that it?
    args: ["-c","10.244.1.157","-l","128k"]
  restartPolicy: Never
  nodeSelector:
    nginx-node: node1
