apiVersion: v1
kind: Pod
metadata:
  name: iperf-dev-s-1
spec:
  containers:
  - name: iperf-dev-s-1
    image: iperf-dev-1
    ports:
    - containerPort: 5201
    imagePullPolicy: IfNotPresent
    #command: ["printenv"] # is that it?
    args: ["-s"]
  nodeSelector:
    nginx-node: node1
