apiVersion: v1
kind: Pod
metadata:
  name: iperf-client-2
spec:
  containers:
  - name: iperf-client-2
    image: iperf-dev-2
    #ports:
      #- containerPort: 5201
    imagePullPolicy: IfNotPresent
    #command: ["printenv"] # is that it?
    args: ["-c",192.168.247.5,"-l","256k"]
  restartPolicy: Never
  nodeSelector:
    nginx-node: node2
